CREATE TYPE public.app_role AS ENUM ('admin', 'user');
CREATE TYPE public.investment_status AS ENUM ('active', 'completed');
CREATE TYPE public.transaction_type AS ENUM ('deposit', 'withdrawal');
CREATE TYPE public.transaction_status AS ENUM ('pending', 'completed', 'rejected', 'failed');

CREATE TABLE public.profiles (
  id uuid PRIMARY KEY,
  email text,
  phone text UNIQUE,
  display_name text,
  avatar_animal text NOT NULL DEFAULT 'cow',
  account_balance numeric(14,2) NOT NULL DEFAULT 0 CHECK (account_balance >= 0),
  deposit_balance numeric(14,2) NOT NULL DEFAULT 0 CHECK (deposit_balance >= 0),
  unclaimed_income numeric(14,2) NOT NULL DEFAULT 0 CHECK (unclaimed_income >= 0),
  available_points integer NOT NULL DEFAULT 0 CHECK (available_points >= 0),
  referral_code text NOT NULL UNIQUE DEFAULT upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8)),
  referred_by uuid,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE ON public.profiles TO authenticated;
GRANT ALL ON public.profiles TO service_role;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.user_roles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  role public.app_role NOT NULL DEFAULT 'user',
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, role)
);
GRANT SELECT ON public.user_roles TO authenticated;
GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.packages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  animal_key text NOT NULL,
  emoji text NOT NULL,
  price_kes numeric(14,2) NOT NULL CHECK (price_kes >= 0),
  daily_income_kes numeric(14,2) NOT NULL CHECK (daily_income_kes >= 0),
  cycle_days integer NOT NULL CHECK (cycle_days > 0),
  total_profit_kes numeric(14,2) NOT NULL CHECK (total_profit_kes >= 0),
  is_free boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  display_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.packages TO authenticated;
GRANT ALL ON public.packages TO service_role;
ALTER TABLE public.packages ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.investments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  package_id bigint NOT NULL REFERENCES public.packages(id),
  price_paid numeric(14,2) NOT NULL,
  daily_income numeric(14,2) NOT NULL,
  days_elapsed integer NOT NULL DEFAULT 0,
  cycle_days integer NOT NULL,
  status public.investment_status NOT NULL DEFAULT 'active',
  last_accrued_on date NOT NULL DEFAULT current_date,
  started_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.investments TO authenticated;
GRANT ALL ON public.investments TO service_role;
ALTER TABLE public.investments ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.transactions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  type public.transaction_type NOT NULL,
  amount_kes numeric(14,2) NOT NULL CHECK (amount_kes > 0),
  status public.transaction_status NOT NULL DEFAULT 'pending',
  provider text NOT NULL DEFAULT 'mpesa',
  provider_reference text UNIQUE,
  merchant_request_id text UNIQUE,
  checkout_request_id text UNIQUE,
  phone text,
  failure_reason text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  processed_at timestamptz,
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT ON public.transactions TO authenticated;
GRANT ALL ON public.transactions TO service_role;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.referral_commissions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  earner_id uuid NOT NULL,
  source_user_id uuid NOT NULL,
  level smallint NOT NULL CHECK (level IN (1, 2)),
  investment_id uuid REFERENCES public.investments(id),
  amount numeric(14,2) NOT NULL CHECK (amount >= 0),
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.referral_commissions TO authenticated;
GRANT ALL ON public.referral_commissions TO service_role;
ALTER TABLE public.referral_commissions ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.points_ledger (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  delta integer NOT NULL,
  reason text NOT NULL,
  investment_id uuid REFERENCES public.investments(id),
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.points_ledger TO authenticated;
GRANT ALL ON public.points_ledger TO service_role;
ALTER TABLE public.points_ledger ENABLE ROW LEVEL SECURITY;

CREATE INDEX investments_user_status_idx ON public.investments(user_id, status);
CREATE INDEX transactions_user_created_idx ON public.transactions(user_id, created_at DESC);
CREATE INDEX transactions_status_type_idx ON public.transactions(status, type);
CREATE INDEX profiles_referred_by_idx ON public.profiles(referred_by);
CREATE INDEX commissions_earner_idx ON public.referral_commissions(earner_id, created_at DESC);

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$;
CREATE TRIGGER profiles_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER packages_updated_at BEFORE UPDATE ON public.packages FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER investments_updated_at BEFORE UPDATE ON public.investments FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER transactions_updated_at BEFORE UPDATE ON public.transactions FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid, _role public.app_role)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = _role)
$$;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated, service_role;

CREATE POLICY profiles_read_own ON public.profiles FOR SELECT TO authenticated USING (id = auth.uid() OR public.has_role(auth.uid(), 'admin'));
CREATE POLICY profiles_insert_own ON public.profiles FOR INSERT TO authenticated WITH CHECK (id = auth.uid());
CREATE POLICY profiles_update_own ON public.profiles FOR UPDATE TO authenticated USING (id = auth.uid()) WITH CHECK (id = auth.uid());
CREATE POLICY roles_read_own_or_admin ON public.user_roles FOR SELECT TO authenticated USING (user_id = auth.uid() OR public.has_role(auth.uid(), 'admin'));
CREATE POLICY packages_read_active ON public.packages FOR SELECT TO authenticated USING (is_active OR public.has_role(auth.uid(), 'admin'));
CREATE POLICY investments_read_own_or_admin ON public.investments FOR SELECT TO authenticated USING (user_id = auth.uid() OR public.has_role(auth.uid(), 'admin'));
CREATE POLICY transactions_read_own_or_admin ON public.transactions FOR SELECT TO authenticated USING (user_id = auth.uid() OR public.has_role(auth.uid(), 'admin'));
CREATE POLICY transactions_create_own ON public.transactions FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid() AND status = 'pending');
CREATE POLICY commissions_read_own_or_admin ON public.referral_commissions FOR SELECT TO authenticated USING (earner_id = auth.uid() OR public.has_role(auth.uid(), 'admin'));
CREATE POLICY points_read_own_or_admin ON public.points_ledger FOR SELECT TO authenticated USING (user_id = auth.uid() OR public.has_role(auth.uid(), 'admin'));

CREATE OR REPLACE FUNCTION public.ensure_my_profile(_email text, _phone text DEFAULT NULL, _display_name text DEFAULT NULL, _referral_code text DEFAULT NULL)
RETURNS public.profiles LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_profile public.profiles; v_referrer uuid;
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Authentication required'; END IF;
  IF _referral_code IS NOT NULL AND length(trim(_referral_code)) > 0 THEN
    SELECT id INTO v_referrer FROM public.profiles WHERE referral_code = upper(trim(_referral_code)) AND id <> auth.uid();
    IF v_referrer IS NULL THEN RAISE EXCEPTION 'Invalid referral code'; END IF;
  END IF;
  INSERT INTO public.profiles (id, email, phone, display_name, referred_by)
  VALUES (auth.uid(), lower(nullif(trim(_email), '')), nullif(trim(_phone), ''), nullif(trim(_display_name), ''), v_referrer)
  ON CONFLICT (id) DO UPDATE SET
    email = COALESCE(public.profiles.email, excluded.email),
    phone = COALESCE(public.profiles.phone, excluded.phone),
    display_name = COALESCE(public.profiles.display_name, excluded.display_name)
  RETURNING * INTO v_profile;
  INSERT INTO public.user_roles (user_id, role) VALUES (auth.uid(), 'user') ON CONFLICT DO NOTHING;
  RETURN v_profile;
END;
$$;
GRANT EXECUTE ON FUNCTION public.ensure_my_profile(text, text, text, text) TO authenticated;

CREATE OR REPLACE FUNCTION public.purchase_package(_package_id bigint)
RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_pkg public.packages; v_profile public.profiles; v_investment uuid; v_l1 uuid; v_l2 uuid; v_amount numeric;
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Authentication required'; END IF;
  SELECT * INTO v_pkg FROM public.packages WHERE id = _package_id AND is_active FOR SHARE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Package unavailable'; END IF;
  SELECT * INTO v_profile FROM public.profiles WHERE id = auth.uid() FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Profile not found'; END IF;
  IF v_pkg.is_free AND EXISTS (SELECT 1 FROM public.investments WHERE user_id = auth.uid() AND package_id = _package_id) THEN RAISE EXCEPTION 'Free package already claimed'; END IF;
  IF NOT v_pkg.is_free AND v_profile.deposit_balance < v_pkg.price_kes THEN RAISE EXCEPTION 'Insufficient deposit balance'; END IF;
  UPDATE public.profiles SET deposit_balance = deposit_balance - v_pkg.price_kes WHERE id = auth.uid();
  INSERT INTO public.investments (user_id, package_id, price_paid, daily_income, cycle_days)
  VALUES (auth.uid(), v_pkg.id, v_pkg.price_kes, v_pkg.daily_income_kes, v_pkg.cycle_days) RETURNING id INTO v_investment;
  IF NOT v_pkg.is_free AND v_profile.referred_by IS NOT NULL THEN
    v_l1 := v_profile.referred_by; v_amount := round(v_pkg.price_kes * 0.15, 2);
    UPDATE public.profiles SET account_balance = account_balance + v_amount WHERE id = v_l1;
    INSERT INTO public.referral_commissions (earner_id, source_user_id, level, investment_id, amount) VALUES (v_l1, auth.uid(), 1, v_investment, v_amount);
    SELECT referred_by INTO v_l2 FROM public.profiles WHERE id = v_l1;
    IF v_l2 IS NOT NULL THEN
      v_amount := round(v_pkg.price_kes * 0.05, 2);
      UPDATE public.profiles SET account_balance = account_balance + v_amount WHERE id = v_l2;
      INSERT INTO public.referral_commissions (earner_id, source_user_id, level, investment_id, amount) VALUES (v_l2, auth.uid(), 2, v_investment, v_amount);
    END IF;
  END IF;
  RETURN v_investment;
END;
$$;
GRANT EXECUTE ON FUNCTION public.purchase_package(bigint) TO authenticated;

CREATE OR REPLACE FUNCTION public.collect_income()
RETURNS numeric LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_amount numeric;
BEGIN
  UPDATE public.profiles SET account_balance = account_balance + unclaimed_income, unclaimed_income = 0
  WHERE id = auth.uid() RETURNING account_balance INTO v_amount;
  IF v_amount IS NULL THEN RAISE EXCEPTION 'Profile not found'; END IF;
  RETURN v_amount;
END;
$$;
GRANT EXECUTE ON FUNCTION public.collect_income() TO authenticated;

CREATE OR REPLACE FUNCTION public.request_withdrawal(_amount numeric, _phone text)
RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_id uuid;
BEGIN
  IF _amount <= 0 THEN RAISE EXCEPTION 'Amount must be greater than zero'; END IF;
  IF _phone !~ '^254[0-9]{9}$' THEN RAISE EXCEPTION 'Use a valid 254 mobile number'; END IF;
  UPDATE public.profiles SET account_balance = account_balance - _amount
  WHERE id = auth.uid() AND account_balance >= _amount;
  IF NOT FOUND THEN RAISE EXCEPTION 'Insufficient account balance'; END IF;
  INSERT INTO public.transactions (user_id, type, amount_kes, phone, provider)
  VALUES (auth.uid(), 'withdrawal', _amount, _phone, 'mpesa') RETURNING id INTO v_id;
  RETURN v_id;
END;
$$;
GRANT EXECUTE ON FUNCTION public.request_withdrawal(numeric, text) TO authenticated;

CREATE OR REPLACE FUNCTION public.accrue_daily_income()
RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_count integer := 0; v_row record; v_days integer; v_credit numeric;
BEGIN
  FOR v_row IN SELECT * FROM public.investments WHERE status = 'active' AND last_accrued_on < current_date FOR UPDATE LOOP
    v_days := LEAST((current_date - v_row.last_accrued_on), v_row.cycle_days - v_row.days_elapsed);
    IF v_days > 0 THEN
      v_credit := v_row.daily_income * v_days;
      UPDATE public.profiles SET unclaimed_income = unclaimed_income + v_credit, available_points = available_points + v_days WHERE id = v_row.user_id;
      UPDATE public.investments SET days_elapsed = days_elapsed + v_days, last_accrued_on = current_date,
        status = CASE WHEN days_elapsed + v_days >= cycle_days THEN 'completed'::public.investment_status ELSE status END,
        completed_at = CASE WHEN days_elapsed + v_days >= cycle_days THEN now() ELSE completed_at END WHERE id = v_row.id;
      INSERT INTO public.points_ledger (user_id, delta, reason, investment_id) VALUES (v_row.user_id, v_days, 'Daily farm activity', v_row.id);
      v_count := v_count + 1;
    END IF;
  END LOOP;
  RETURN v_count;
END;
$$;
REVOKE ALL ON FUNCTION public.accrue_daily_income() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.accrue_daily_income() TO service_role;